### ISSUE TITLE
[문의] 특정 언론사 fetching 오류 문의드립니다 (여성소비자신문).

### ISSUE THREAD

**Issue by stephkcho** [seongjinme/naver-news-fetching-bot#5]
안녕하세요, 

정말 덕분에 편리하게 업무를 하게 되어 우선 감사의 말씀 드립니다. 
현재 Slack으로 '미래에셋생명' 키워드를 등록하여 네이버 최신 뉴스를 받고 있는데요, 

오늘 2023.08.23자 뉴스 중 '여성소비자신문' 기사만 fetching이 되지 않아 슬랙으로 메신저가 오지 않았습니다.
해당 언론사는 올려주신 [naver-news-fetching-bot](https://github.com/seongjinme/naver-news-fetching-bot/tree/main)
/source.gs 에 잘 등록이 되어 있는데도 fetching이 되지 않은 것 같아 문의드립니다.

기사 원문 URL 도 첨부드립니다. 
 
http://www.wsobi.com/news/articleView.html?idxno=211758

네이버 최신 뉴스 키워드 '미래에셋생명' 설정 시 뜨는 해당 기사

![230823 미래에셋생명 네이버최신순뉴스](https://github.com/seongjinme/naver-news-fetching-bot/assets/142973184/e160b12d-8c73-412f-a5f7-1c6e49952c5c)

**Comment by seongjinme** [comment]
안녕하세요.

방금 확인해보니 현재 배포된 코드 기준으로 같은 검색 키워드("미래에셋생명")에서 '여성소비자신문' 기사도 정상적으로 fetching되는 것을 확인했습니다.
<img width="1326" alt="뉴스봇 실행 결과" src="https://github.com/seongjinme/naver-news-fetching-bot/assets/73219583/8587b5c2-51a1-4a33-9856-8d9e695dc698">
<img width="673" alt="네이버 검색 결과" src="https://github.com/seongjinme/naver-news-fetching-bot/assets/73219583/99257fca-4e80-421a-b549-1fe12f4d19dc">

이 뉴스봇 스크립트는 네이버의 검색 API를 이용하여 결과물을 받아온 뒤, 
이전에 실행되었던 가장 최근의 시각을 기준으로 그 이후에 올라온 뉴스를 fetching하도록 하고 있습니다.
매체명이 source.gs에 등록되어 있지 않을 경우 해당 도메인명을 노출하도록 되어 있으므로, 
매체 등록 유무는 fetching 여부에 영향을 주지 않습니다.

다만 코드를 검토해보니, 상당히 드문 경우겠으나 아래와 같은 시나리오에 의한 문제일 것으로 예상됩니다.
1. 네이버 뉴스에 업로드 된 시각이 timestamp 기준으로 완전히 똑같은 복수의 기사들이 존재하며
2. 어떠한 이유로든 이들 중 일부만 fetching된 상태로 뉴스봇 실행이 종료되었다면, 다음번 실행때 나머지 기사들이 누락될 가능성이 있습니다.

이에 대한 해결 방안은 별도로 검토해 보겠습니다.
감사합니다.

**Comment by stephkcho** [comment]
헙 안녕하세요, 

정말 빠른 피드백 감사합니다! 
메일도 별도로 보내드렸는데ㅠㅠ 그 사이에 회신 확인을 못한 점 죄송합니다. 
해당 건에 대해 별도로 검토 해보신 후 업데이트가 있을 시 다시 코멘트 달아주시면 확인하겠습니다!

정말정말 감사합니다!

**Comment by seongjinme** [comment]
안녕하세요. 마지막으로 코멘트를 드린 후로 어느덧 1년이 훌쩍 지났네요. 
말씀주셨던 문제를 해결한 새 버전을 뒤늦게나마 배포했습니다. 한 번 사용해 보시면 좋겠습니다. 감사합니다 🙏
