### ISSUE TITLE
다중 키워드 검색 문의

### ISSUE THREAD

**Issue by tmdwo5811** [seongjinme/naver-news-fetching-bot#6]
현재는 1개 키워드만 설정이 가능해 보이는데 다중 키워드로 사용 할 수 있는 방법이 있을까요?

구글 스크립트를 여러개 등록 하는 방법 뿐일까요?

**Comment by seongjinme** [comment]
안녕하세요.
문의주신 사항에 대해서는 아래 링크에 포함된 저의 답변 내용을 참고하시면 좋을 것 같습니다.
https://github.com/seongjinme/blog-comments/discussions/8#discussioncomment-3101054

제 견해를 요약드리자면 이렇습니다.
* 하나의 인스턴스로 다중 검색키워드에 대한 뉴스를 받아오는 일이 기술적으로 가능하긴 합니다만,
* 이렇게 코드를 변경하실 경우 네이버 검색 API 및 채팅 솔루션별 webhook의 시간당 호출 한도를 반드시 고려하셔야 합니다.
* 이런저런 호출 한도 제한을 우회하시려면, 말씀대로 키워드 별로 등록하시는 편이 안전합니다.
