### ISSUE TITLE
네이버가 아닌 구글API로 활용할 수 있는 지 문의드립니다

### ISSUE THREAD

**Issue by stephkcho** [seongjinme/naver-news-fetching-bot#9]

**Comment by seongjinme** [comment]
안녕하세요. 답이 많이 늦었네요. 구글 뉴스는 공식 API가 제공되지 않고, 다만 몇몇 서드파티 API들이 유료로 서비스되고 있습니다. 네이버 검색 API와는 데이터를 주고 받는 방식이 여러모로 다를 것이기 때문에 코드 수정이 많이 필요할 것 같네요.
